### ISSUE TITLE
No language tabs on TranslatableStackedInline inlines

### ISSUE THREAD

**Issue by jeffmarshall** [KristianOellegaard/django-hvad#102]
models.py:

``` python
from django.db import models
from django.utils.translation import ugettext_lazy as _
from hvad.models import TranslatableModel, TranslatedFields



class Page(models.Model):
    slug = models.SlugField()

    class Meta:
        verbose_name = _('Page')
        verbose_name_plural = _('Pages')

    def __unicode__(self):
        return " Page: %(slug)s" % {"slug": self.slug}


class Text(TranslatableModel):
    """
     translatable text. Meant as a multilingual flatblocks thing.
    """

    slug = models.SlugField()
    page = models.ForeignKey(Page, blank=True, null=True)

    translations = TranslatedFields(
        text = models.TextField()
    )

    class Meta:
        verbose_name = _('Text')
        verbose_name_plural = _('Texts')

    def __unicode__(self):
        return " Text: %(slug)s" % {"slug": self.slug}
```

admin.py:

``` python
from django.contrib import admin
from hvad.admin import TranslatableStackedInline, TranslatableAdmin
from generic.models import Text, Page



class TextInline(TranslatableStackedInline):
    model = Text
    extra = 1


class PageAdmin(admin.ModelAdmin):
    inlines = [TextInline]


admin.site.register(Page, PageAdmin)
admin.site.register(Text, TranslatableAdmin)
```

Screenshot:
![hvad stacked inline admin](http://f.cl.ly/items/2M0i2W2X44171e3W2s32/Screen%20Shot%202013-02-26%20at%207.58.48%20PM.png)

**Comment by urtzai** [comment]
Is this issue solved already? Thank you

**Comment by spectras** [comment]
Hello urtzai,
The state is about the same: you can show inlines for an untranslated parent model, but they will be in current language and you cannot change that. At least, not without adding custom code.

Even before technical feasibility, adding this feature would require specifying it before. What inlines should be shown? What if an inline exists in a language but not the one the user selects? What happens if I delete an inline, should it remove it completely or just remove the translation in current language? How to make clear which it is to the user? What should the UX look like to create a new translation for an existing inline (as opposed to creating a new, different inline in another language)?

Admin definitely needs some love.

**Comment by urtzai** [comment]
My problem is that I use 3rd party modules like [django-photologue](https://github.com/jdriscoll/django-photologue) so, I don't want to customize directly these modules in order to maintain the integrity in new updates.

But I need new fields or even existing ones multilingual. The way Photologue recommends to inherit their models [is the following](https://django-photologue.readthedocs.io/en/stable/pages/customising/models.html). So respecting this, I built this workaround solution. It's not a good solution but fits my needs:

## forms.py

```
from django import forms
from photologue.models import Photo
from django.conf import settings

MULTISITE = getattr(settings, 'PHOTOLOGUE_MULTISITE', False)

class PhotoAdminExtendedForm(forms.ModelForm):

    class Meta:
        model = Photo
        if MULTISITE:
            exclude = []
        else:
            exclude = ['sites','caption']
```

I edit the form to hide the original caption field.

## models.py

```
class PhotoExtended(TranslatableModel):
    photo = models.OneToOneField(Photo, related_name='extended')

    translations = TranslatedFields(
        caption=models.TextField(_('caption'), blank=True)
    )

    class Meta:
        verbose_name = _('Multilingual Caption')
        verbose_name_plural = _('Multilingual Captions')

    def __unicode__(self):
        return self.photo.title
```

I create the extended model to add new multilingual fields.

## admin.py

```
from .models import PhotoExtended
from .forms import PhotoAdminExtendedForm
from hvad.admin import TranslatableStackedInline
from photologue.admin import PhotoAdmin as PhotoAdminDefault
from photologue.models import Photo

class PhotoExtendedInline(TranslatableStackedInline):
    model = PhotoExtended
    can_delete = False


class PhotoAdmin(PhotoAdminDefault):
    form = PhotoAdminExtendedForm
    inlines = [PhotoExtendedInline, ]

admin.site.unregister(Photo)
admin.site.register(Photo, PhotoAdmin)
```

I register new admin for Photo model with multilingual inlines and hiding an original caption field

## stacked.html (templates/admin/hvad/edit_inline/stacked.html):

```
{% load i18n %}

{% get_available_languages as LANGUAGES %}


<div class="hvad-language-tabs nani-language-tabs">
    {% for code,lang in LANGUAGES %}
    <input type="hidden" class="language_button selected" name="{{lang.0}}" />
    {% if not request.GET.language and code == request.LANGUAGE_CODE or request.GET.language and code == request.GET.language %}
    <span class="current" style="display: inline-block; padding: 5px 15px;border: 1px solid #ccc;border-bottom: none;position: relative;left: 0px;top: 1px;font-weight: bold;">{{lang}}</span>
    {% else %}
    <span class="available" style="display: inline-block; padding: 5px 15px;border: 1px solid #ccc;border-bottom: none;position: relative;left: 0px;top: 1px;font-weight: bold;"><a href="?language={{code}}">{{lang}}</a></span>
    {% endif %}
    {% endfor %}
</div>

...

I override stacked.html to add language changing tabs. Quite simple and awful, but as I said, fits my needs.

Result image:
![django-hvad_stacked](https://cloud.githubusercontent.com/assets/1741252/20389808/d1616728-accb-11e6-9ff0-3f3d250a6dbd.png)

**Comment by spectras** [comment]
Well, as you see, the way it works depends a lot on what and where you want to link those inlines to.

I guess for your specific example it would be possible to customize the admin more, and display a [TranslationFormSet](https://django-hvad.readthedocs.io/en/latest/public/forms.html#translationformset) instead. It would not be an inline though. You would have to load it alongside the changeform of your main model. I am not very accustomed to Django admin though so I guess you'd come up with a way to do this faster than I would.
