### ISSUE TITLE
Suggestion: Deprecate LanguageOverride to encourage use of django.utils.translation.override instead

### ISSUE THREAD

**Issue by mkoistinen** [KristianOellegaard/django-hvad#226]
They seem do the exact same thing, and Django's context manager has been in-place since v1.4.

**Comment by spectras** [comment]
Well yes, especially as projects should not be using the LanguageOverride thing, since it is an internal tool used only in the testsuite (it lives in `./test_utils/context_managers.py`). It is not needed anymore as, like you noticed, Django now provides it.

Given it is part of the testsuite that is not even distributed in the package, it could be removed right away. But I'll give it a short deprecation cycle just in case.

Thanks for noticing and reporting that :)
