### ISSUE TITLE
Issue in multilanguage manutomany fields

### ISSUE THREAD

**Issue by kartikdanidhariya** [KristianOellegaard/django-hvad#229]
hi,
i am usind hvad in my project for multilanguage (en/fr)

i create on application "Businesspage"

models.py

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
import datetime
from hvad.models import TranslatableModel, TranslatedFields, TranslationManager
import re
from django.core.urlresolvers import reverse

class Product(TranslatableModel):
    
   class BusinessPage(TranslatableModel):
    
    translations = TranslatedFields(
    user = models.ForeignKey('auth.User', verbose_name=_('User'), null=True, blank=True),
    #slug = models.SlugField(max_length=100, unique=True, verbose_name=_('Slug')),
    slug = models.SlugField(max_length=100, verbose_name=_('Slug')),
    logo = models.ImageField(upload_to='business_page/logo/',blank=True, null=True, verbose_name = _('Business Logo')),
    business_name = models.CharField(max_length=100,verbose_name = _('Business Name')),
    tag_line = models.TextField(verbose_name = _('Tag Line')),
    business_photo = models.ImageField(upload_to='business_page/photo/',blank=True, null=True, verbose_name = _('Business Photo')),
    video_url = models.URLField(max_length=150, null=True, blank=True, verbose_name = _('Youtube Video Url')),
    des = models.TextField(verbose_name = _('Business Description')),
    #add = models.TextField(verbose_name = _('Address'))
    map_lat = models.CharField(verbose_name = _('Lattitude'),  max_length=25, blank=True, null=True),
    map_long = models.CharField(verbose_name = _('Longitude'),  max_length=25, blank=True, null=True),
        
        )

 def __unicode__(self,):
        return str(self.business_name)
    
    def get_absolute_url(self):
        slug = self.slug
        return reverse('business_page_preview', kwargs={'slug': slug})
    
    def save(self, *args, **kwargs):
        new_url = re.sub('watch\?v=','v/',self.video_url)
        if new_url:
            self.video_url = new_url
            super(BusinessPage, self).save(*args, **kwargs)

and ssecond application is "Product"

models.py

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
import datetime
from hvad.models import TranslatableModel, TranslatedFields, TranslationManager
import re
from django.core.urlresolvers import reverse

class Product(TranslatableModel):
    
    translations = TranslatedFields(
    #user = models.ForeignKey('auth.User', verbose_name=_('User'), null=True, blank=True),
    business_page = models.ManyToManyField('business_page.Businesspage'),
    product_name = models.CharField(max_length=100,verbose_name = _('Product Name')),
    pro_image = models.ImageField(upload_to='products/',blank=True, null=True, verbose_name = _('Product Image')),
    price = models.CharField(max_length=15,verbose_name = _('Price')),
    des = models.TextField(verbose_name = _('Product Description')),
    dis_code = models.CharField(max_length=10,verbose_name = _('Discount Code')),
    pub_date = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name = _('Publish Date')),
    modified_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name = _('Modified Date')),
        )
  def __unicode__(self,):
        return str(self.product_name)
    
    def get_absolute_url(self):
        id = self.id
        return reverse('business_page_preview', kwargs={'id': id})
    
    def save(self):
        if not self.id:
            self.created = datetime.date.today()
        self.updated = datetime.datetime.today()
        
        super(Product, self).save()
i am add business_page through TranslatableModelForm so when i add record in en language so it only add in english language record after when i change language so it save another record in french it's not save in same record,because of this reason when i try to add object in "product" so it's give following error

"NoTranslationError at /en/admin/products/product/add/

Accessing a translated field requires that the instance has a translation loaded, or a valid translation in current language (en) loadable from the database"

i think this error because of the business_page record in not available in both language 

so how i can solve this problem,
pls help!!!

Thanks in advance!!!

**Comment by spectras** [comment]
Hello,

Well, before addressing the issue, let's make sure I fully understand your environment.
Unless I am mistaken, it looks some of your fields should not be translatable?
For instance, unless you want each language to have a different publication date, the publication date should be untranslatable.

Here is a suggestion, but the exact fields that should change based on the language will, of course, depend on your specific business requirement:
```python
class BusinessPage(TranslatableModel):
    user = models.ForeignKey('auth.User', verbose_name=_('User'), null=True, blank=True),
    logo = models.ImageField(upload_to='business_page/logo/',blank=True, null=True, verbose_name = _('Business Logo')),
    video_url = models.URLField(max_length=150, null=True, blank=True, verbose_name = _('Youtube Video Url')),
    slug = models.SlugField(max_length=100, verbose_name=_('Slug')),

translations = TranslatedFields(
    business_name = models.CharField(max_length=100,verbose_name = _('Business Name')),
    business_photo = models.ImageField(upload_to='business_page/photo/',blank=True, null=True, verbose_name = _('Business Photo')),
    tag_line = models.TextField(verbose_name = _('Tag Line')),
    des = models.TextField(verbose_name = _('Business Description')),
    #add = models.TextField(verbose_name = _('Address'))
    map_lat = models.CharField(verbose_name = _('Lattitude'),  max_length=25, blank=True, null=True),
    map_long = models.CharField(verbose_name = _('Longitude'),  max_length=25, blank=True, null=True),
    )

    def unicode(self):
        return self.safe_translation_getter('business_name', str(self.pk))

    def get_absolute_url(self):
        return reverse('business_page_preview', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        new_url = re.sub('watch\?v=','v/',self.video_url)
        if new_url:
            self.video_url = new_url
            super(BusinessPage, self).save(*args, **kwargs)
```
I assumed your slug does not depend on the language. If you also translate the slug, then it is a bit more complex as it means `get_absolute_url()` could fail if the business page is not translated in the current language.
If you need a translated slug, please tell me and I will add some sample code for that as well :)

So, well, based on the error and your example, I cannot be 100% sure of what is happening, but I guess it has something to do with either your `unicode()` or your `get_absolute_url` methods. The way you wrote them, they absolutely require that a translation exists in current language so they can return a meaningful result. That means you must either:
* ensure they are never called without a language properly loaded.
* or change them to gracefully handle the case they are called but the language does not exist.

There are several ways to do this, from using fallbacks when loading your objects (so that objects with no translation in current language are loaded with another language), simply not loading objects with another language, or handling that case manually.

By the way, could you also post the form and view you use?
You can enclose your code with "\`\`\`python" and "\`\`\`" to make it look nice.

**Comment by kartikdanidhariya** [comment]
Thanks for your sugestion but i have question how i deal with the form.py because i get all the data from end user through form 
so,pls suggest me!!!

**Comment by spectras** [comment]
Alright, so that depends on what you are trying to achieve.

- your form may display everything in one language. Either everything in English or everything in French.
    - what happens for objects that do not exist in current language then ? Are they shown in the other language, or are they hidden?
- your form may show both language at the same time. You probably need some custom javascript so it looks nice (like, creating tabs or something).

First option is pretty easy to achieve, but you must know which language you want to use. Either you ask the user which language he wants, or you choose based on his browser preferred language or you enforce a language based on business requirements (like "English is our main language, so everything must be English by default").

Second option allows editing both English and French on the same form, but it is more complex to code, and you risk confusing users who are not aware they should fill in both languages. That's usually more suited for some administration backend.

**Comment by spectras** [comment]
Given you've not answered after a month, I assume you managed to solve your problem so I will close the issue. Please feel free to post again, I'll repoen as needed.

**Comment by kartikdanidhariya** [comment]
HI ,
i want English object by default and if that same id object not exists in french so it give us error
"matching query does not exist."
now i want to load English language object if french language object is not exists in database 
so how can i do that
pls help!!
Thanks in advanced!!!

**Comment by spectras** [comment]
Hi,
I'm really sorry but I do not understand your issue. If French is your native language, maybe try to explain in French, I can speak French too. I will translate back into English for other readers.

I would need to know, to the very least:

* Is this new post connected to your initial issue? / *Ce nouveau message est-il lié au problème initial ?*
* What exactly you are trying to achieve? / *Qu'est-ce que tu souhaites obtenir exactement ?*
* Where in your code is your issue? View, form, admin? / *Dans quelle partie de ton code se situe le problème ?*
* Are you dealing with a single object or a list of objects? / *Est-ce que ton problème concerne un objet unique, ou un listing d'objets ?*
