### ISSUE TITLE
Support for multi-table inheritance

### ISSUE THREAD

**Issue by sephii** [KristianOellegaard/django-hvad#230]
I couldn't find anything in the docs so I don't know what's the supposed status of this, but from what I experienced, multi-table inheritance doesn't work. Suppose you have the following model:

```python
class BaseBook(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=100)
    )

class Book(BaseBook):
    chapters = models.IntegerField()
```

Hvad will complain:
```
django.core.exceptions.ImproperlyConfigured: No TranslatedFields found on <class 'demo.models.Book'>, subclasses of TranslatableModel must define TranslatedFields.
```

And if you define `TranslatedFields`, you then get an error:
```
django.core.exceptions.FieldError: Local field 'language_code' in class 'BookTranslation' clashes with field of similar name from base class 'BaseBookTranslation'
```

It would be nice to have support for this, although I have no idea how difficult it would be to implement. And if the effort to achieve this is too important, I guess a note should be added to the docs.

**Comment by spectras** [comment]
Hello,

This is the last step in the inheritance scheme indeed. At the moment, hvad supports inheritance with abstract models and proxy models. Concrete inheritance is not yet supported (unless the only translatable model is the last of the inheritance chain).

I think this is the first time someone requests it, because usually this kind of pattern is better implemented using Django's abstract models. (adding `abstract = True` to your `BaseBook`). Concrete inheritance leads to very complex queries on the database side, which would get even more complex with translations.

Despite that, I think we should add it, at least so implementation of Django inheritance schemes is complete. I'm adding it to the todo list, but I cannot give you a date right now. In the meantime, may I suggest you check whether your use case could leverage abstract models instead?

**Comment by spectras** [comment]
Thoughts to myself for future reference: implementing this would deal mostly with three main aspects:
- model creation, to properly setup concrete translation inheritance.
- model instantiation, to handle shared model polymorphism.
- query string navigation, to ensure inherited tables are followed correctly.

**Comment by spectras** [comment]
I added a note in the documentation for now (it will show up soon).
I thought about multi-table inheritance again and it looks hard to implement, because it creates edge cases, for which desired behaviors are not clear.

For instance, given model `Place` and model `Restaurant`, the latter inheriting from the former, and both being translatable, most edge cases revolve around the parent being translated in a given language and not the child, or vice versa.

* what should happen when trying to fetch a restaurant in, say German, if the restaurant is not translated in German but the place is? Should it fail? Should it succeed and load an incomplete instance?
* if it should fail, how would one add a translation for the restaurant without overwriting that of the place?
* how should hvad react to having a partly-translated instance?
* how would you go about deleting just the Restaurant translation but not the Place translation?

Those would probably require new APIs or a heavy, compatibility-breaking refactor of existing API.
It also sounds pretty hard on the database, a mere traversal of such a construction requiring 4 separate JOINs.

I came to the conclusion that it is very unlikely hvad will support multi-table inheritance, unless someones comes up with solutions to all those issues. I will try to have hvad catch them though, so it can raise an explicit error.
