### ISSUE TITLE
Proxy models and admin list_display don't seem to work togeter

### ISSUE THREAD

**Issue by gone** [KristianOellegaard/django-hvad#234]
I have a situation like this:

```
#models.py
class Content(TranslatableModel):
    translations = TranslatedFields(
        title = models.CharField(max_length=500),
    )

class Article(Content):
    class Meta:
        proxy = True

#admin.py
class ContentAdmin(TranslatableAdmin):
   list_display = ('title', )

class ArticleAdmin(ContentAdmin):
    pass
```

And attempting to run server or shell gets me:

```
hvad.exceptions.WrongManager: To access translated fields like 'title' from an untranslated model, you must use a translation aware manager. For non-translatable models, you can get one using hvad.utils.get_translation_aware_manager.
For translatable models, use the language() method.
```
Removing title from list_display on content Admin fixes the error

**Comment by spectras** [comment]
Hello,

Support for translated fields in admin options is a long standing issue with no obvious solution, due to the way the admin app works. Issue #187 tracks this, though given how often the admin app API changes, it has been stalled for a while.

Which version of Django are you using? The inner workings of admin app change alot depending on Django version. Also, could you please provide the stack trace that comes with the WrongManager exception? At least the parts inside hvad and django?

**Comment by spectras** [comment]
Hello,
I'll close this as the main issue of admin interactions is already tracked in #187, and I've not heard from this specific case for a couple of weeks.
Please feel free to tell if you need it reopened.
