### ISSUE TITLE
How to unique_together

### ISSUE THREAD

**Issue by SashaBorandi** [KristianOellegaard/django-hvad#257]
Does not work:

```python
class City(TranslatableModel):
    country = models.ForeignKey(Country)

    translations = TranslatedFields(
        name = models.CharField(max_length=255),
        slug = models.SlugField(max_length=255)
    )

    class Meta:
        unique_together = [('country', 'name')]
```

**Comment by spectras** [comment]
Hello,

As the error message you got probably said, **Constraints in Meta.unique_together cannot mix translated and untranslated fields"**.

For `unique_together` and `index_together`, each grouping may have either translatable or non-translatable fields, but not both. This is because of the way SQL databases work. It is impossible to set up a constraint that span multiple tables (here, the main object and its translations).

**Comment by SashaBorandi** [comment]
thanks
