### ISSUE TITLE
incorrect join types for nullable translated relations with an OR Q query

### ISSUE THREAD

**Issue by tdyer-aio** [KristianOellegaard/django-hvad#259]
Assume:
I have a database that keeps track of movies and tv shows
Movies and tv shows are stored in the same table.
movies have genres, (M2M field) and tv shows have a relation to Series which have genres (M2M field)
Genre's are translatable, but VideoAsset isn't

I want to filter to assets that belong to a given genre.

`genre_query = Q(genres__in=list_genres) | Q(series__genres__in=list_genres)`

`VideoAssets.objects.filter(genre_query)`
will generate a query that uses LEFT JOIN to join the two genre tables.

`get_translation_aware_manager(VideoAssets).filter(genre_query)` on the other hand will use INNER JOIN's and as a result no results would be obtained.

**Comment by spectras** [comment]
Hello, thanks for reporting here.

I believe this kind of query cannot be built using the translation aware manager. The translation aware manager assumes all of the translatable objects touched by the query must be translated. Basically, you take your unaware request, and you add at the end the phrase `and all of that must happen exclusively in the English/German/... realm`.

So your query, as understood by hvad's translation manager, means:
- It has a genre in current language, AND it has a series' genre in current language, AND
- either that genre is in `list_genre` or that series' genre is in `list_genre`

A choice had to be made as to whether the translation condition was applied to the query as a whole or piece by piece, as both are valid and useful possibilities (in fact, it's used that way in several projects). It turns out it is pretty much useless for your use case, unfortunately.

So, how you can handle that?
- Well, to begin with, as long as you're not using translated fields in your request, you should not use the translation aware manager. So for you example, just stick to regular manager.
- You can use subqueries. The translation-aware manager applies its translation awareness to the whole query. If you need to split that, you can generate two subqueries. Imagine, for instance, your `list_genres` was a list of names instead of the list of actual genre objects. You could do this:
```python
genre_qs = get_translation_aware_manager(Genres).filter(name__in=list_genres)
genre_query = Q(genres__in=genre_qs) | Q(series_genres__in=genre_qs)
result = list(VideoAssets.objects.filter(genre_query))
```
This will execute a single query, with two subqueries in it. Performance should be good, especially if you use PostgreSQL, which really shines at optimizing out simple subqueries.

I hope this helps. I will keep this issue in mind when we set out for refactoring the queryset internals and hopefully I'll come up with a solution for customizing this kind of things. That's still a couple of months ahread, though.

**Comment by tdyer-aio** [comment]
Sounds great! We are using MySQL due to some legacy PHP code and can't switch to postgresql just yet.

Thanks, I will look for a more performant workaround.

**Comment by spectras** [comment]
By the way, the TranslationAwareManager is older than most other pieces of hvad, which have been updated and refactored since. Be sure to check the results you get while using it, and don't hesitate to come here if you have trouble on the way.
