### ISSUE TITLE
How to delete one translation model?

### ISSUE THREAD

**Issue by trungdq88** [KristianOellegaard/django-hvad#274]
Say I have a shared model with multiple translation models, how do I delete 1 translation model base on the language code?

To be specific I want to do something like this:

      MyModel.delete_translation('en')

The closest thing I found in the docs is [`delete_translations`](http://django-hvad.readthedocs.org/en/latest/public/queryset.html?highlight=delete#delete_translations) which deletes all the translation models (I want to delete only one).

If hvad does not support delete one translation model, the question is why?

**Comment by spectras** [comment]
Hello,

The `delete_translations` is the right one, it delete all translations matching the query, so all you have to do is filter them first. Here is how you would do it:
```python
# Delete a single translation
MyModel.objects.language('de').filter(pk=42).delete_translations()
# or, if you already have the object loaded
MyModel.objects.language('de').filter(pk=instance.pk).delete_translations()

# Delete several translations at once
MyModel.objects.language('all').filter(pk=42, language_code__in=['de', 'fr', 'en']).delete_translations()

# An alternate way that also works
instance.translations.filter(language_code__in=['de', 'fr']).delete()
```
As always with Django, the affected translations will be deleted from the database but remain in your loaded instance until it goes out of scope.

As a sidenote, it is your responsibility to ensure you do not delete all translations: there must always be at least one translation for an object, otherwise hvad will raise warnings.

Please tell me if you have any issue with it :)

**Comment by trungdq88** [comment]
Thank you for your response. I think this should be placed as an example in the README. I have created a pull request for this in case you want to do it: https://github.com/KristianOellegaard/django-hvad/pull/275
