### ISSUE TITLE
Integrating hvad into an existing app

### ISSUE THREAD

**Issue by elenaoat** [KristianOellegaard/django-hvad#277]
If I "plug in" into my application and modify an already existing field (i.e., make it translatable), and I make migrations, the data is lost. This is obviously happening because the field is being deleted and a new table is created. How could one integrate hvad into an already existing app, without losing the data for the fields that become translatable?

**Comment by spectras** [comment]
Hello,

This is a process that requires 4 Django migration steps:
 * Add translations, without touching existing fields. You cannot use the final field names yet, since they will collide with untranslated ones. Just add some `_temp` suffix.
 * Create a data migration. It should load each untranslated object, create a translation, copy over relevant fields and save the object. Not optimal, but unless you have hundreds of thousands of entries, that should do. If you do have more, you'll probably want to manually craft optimized SQL queries.
 * Drop the legacy fields.
 * Rename translated fields to their final names.

There is a gotcha though: core hvad features are not available inside a migration. This means you have to directly use the translation model. Here is a sample [data migration](https://docs.djangoproject.com/en/1.9/topics/migrations/#data-migrations) function:
```python
from django.db import migrations, models

def add_translations(apps, schema_editor):
    Book = apps.get_model("bookapp", "Book")
    BookTranslation = Book._meta.translations_model
    # if previous line does not work, comment it out and try following line instead:
    # BookTranslation = apps.get_model("bookapp", "BookTranslation")
    for book in Book.objects.all():
        BookTranslation.objects.create(
            language_code='en',
            title_temp=book.title,
            description_temp=book.description
        )

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('yourappname', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names, migrations.RunPython.noop),
    ]
```
I did not test it, so it may require some tweaking, but that's the idea.

**Comment by spectras** [comment]
(just updated the code sample, there was an obvious mistake in it)

**Comment by elenaoat** [comment]
Thanks spectras for your quick and clear reply, I will take a look at it. Will let you know if anything isn't clear.

**Comment by elenaoat** [comment]
I just tried the above, but unfortunately we are still using Django 1.6 and there is nothing about data migrations for this version of Django in documentation (or am I wrong?). I decided that I would instead create those temporary fields and just write a script to copy data from untranslated fields to translated ones.

**Comment by spectras** [comment]
Before Django 1.7, this feature was provided by a third party package, `django-south`. Its syntax was a bit different though and unless you already use it, there would be no point starting now.

A custom script would work too, or even directly altering the tables in the database as well. Depends on what you are most comfortable with.

**Comment by elenaoat** [comment]
Yes, in the end I have just altered the tables directly in the shell as it seemed like the quickest and easiest way to get things done.

**Comment by spectras** [comment]
Closing now, feel free to reopen as needed.

**Comment by claudep** [comment]
This should be in the docs!
