### ISSUE TITLE
Serializing Foreign Key Objects with TranslatedFields Fails

### ISSUE THREAD

**Issue by inakhostin** [KristianOellegaard/django-hvad#287]
I have the following scenario and I get a **NoTranslationError** exception with message 

> Accessing a translated field requires that the instance has a translation loaded, or a valid translation in current language (fr) loadable from the database

I have "Collection" and "Attribute" models, both are TranslatableModels and Collection has a "ManyToManyField" relationship with Attribute, following is my serializers and view. 

The serializers:
```
class AttributeSerializer(TranslatableModelSerializer):
    label = serializers.SlugRelatedField(source='parent', read_only=True,
                                         slug_field='label')
    value = serializers.ReadOnlyField(source='label')
    tag = serializers.ReadOnlyField(source='materialized_path')

    class Meta:
        model = Attribute

class CollectionSerializer(TranslatableModelSerializer):
    metadata = AttributeSerializer(source='attributes', many=True)
    class Meta:
        model = Collection
        fields = ('uuid', 'name', 'label', 'description', 'slug',
                  'start_date', 'end_date', 'metadata',)                  
```

The view:
```
class CollectionView(APIView):

    def get(self, request, format=None, slug=None):
        collection = Collection.objects.language('fr').all()
        serializer = CollectionSerializer(collection, many=True)
        return Response(serializer.data)
```

The problem is with the translation of the Attributes of a Collection. If I query the Attributes directly and create a serializer from the results, there is no exception, but when I query Collection and create the Attribute serializer from the Collection's related Attributes I get the exception. 

P.S. I am very new to Django and everything about it, I might not be able to help much with diagnosing the problem.

**Comment by spectras** [comment]
Hello,
This is probably some of the trickiest things to get right. I'm not 100% certain from just what you provided, but it seems your issue could arise as follows:

1) the view only fetches the collection.
2) therefore, DRF attempts to load Attributes by itself. It will not fetch translations when doing this.

So far, it would not be a problem, except it would be a bit inefficient, because…

3) the translations will be fetched, one by one, when serializing each attribute.

However, if for some reason one of the attributes is not translated in current language (here, `fr`), step 3 will fail with the error you see.

You should be able to fix the issue by prefetching explicitly the attributes with their translation, in the view, like this:

```python
    from django.db.models import Prefetch
    collections = Collection.objects.language('fr').prefetch_related(
        Prefetch('attributes', queryset=Attribute.objects.language('fr')
    )
```

This will have step #1 prefetch the attributes, properly filtered so only those that are translated in French are returned, and they are returned with the translation loaded.

I hope it helps.

**Comment by inakhostin** [comment]
Hello, Thank you very much for your help, you were absolutely right about missing Attribute "fr" translation being the source of the problem. Thank you so much for the fix as well, but in my case a missing translation is not an acceptable use case so I ended up looking for the missing translations and created the records. Thank you again, I will close this issue.
