### ISSUE TITLE
Error: "Wrong Manager" from template when accessing get_translation_aware_manager result

### ISSUE THREAD

**Issue by nuarhu** [KristianOellegaard/django-hvad#288]
Hi!

I've just reactivated an old project that was using an old version with Django 1.6.7, Django CMS 3.0.5 and Django Hvad 0.4.1.

After upgrading all components, my codebase now uses: Django 1.9.4, CMS 3.2.3, and Hvad 1.5.0.

After changing some issues with the admin I'm now facing a problem when adding context data to my templates that fetch a list of regular Django models that have foreign key relations to TranslatableModels.

Basically, the queryset that I add to the context is created using `get_translation_aware_manager(models.KnowledgeElement).language()`.

`KnowledgeElement` is a regular Django model that defines custom CMS placeholders and has foreignkey relations to the TranslatableModels `OperatingLevel` and `Topic`.

```
class KnowledgeElement(KnowbasePage):
    operating_level = models.ForeignKey(OperatingLevel, null=False, related_name="%(class)s_related",
                                        verbose_name=_("Handlungsebene"))
    topic = models.ForeignKey(Topic, null=False, related_name="%(class)s_related", verbose_name=_("Thema"))
```

Both `OperatingLevel` and `Topic` derive from the same abstract model and that abstract model defines the following translations:

```
class ClassificationModel(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(_('Name'), max_length=255), null=True, blank=True,
        slug=models.SlugField(_('Slug'), max_length=255, null=True, blank=True,
                              help_text=_('Wird automatisch aus dem Namen generiert und ist Teil der URL. Sollte nur '
                                          'überschrieben werden, wenn die URL zu lang werden würde.')),
    )

    class Meta:
        abstract = True
        ordering = ('name',)
        unique_together = (('name', 'language_code'), ('slug', 'language_code'))
```

When I add the following to my template context:

    def get_context_data(self, **kwargs):
        kwargs['placeholder_language'] = get_language() or settings.LANGUAGES[0][0]
        kwargs['related_objects'] = get_translation_aware_manager(models.KnowledgeElement).language().filter(operating_level=self.oplevel).all()
        return super().get_context_data(**kwargs)

The following template code throws the error:

```
{% block navigation %}

{% if related_objects %}    <------------------ throws WrongManager
    <div class="navigation">

        <h2>{% blocktrans with name=object.name %}
            Themen in der Rubrik {{ name }}:
        {% endblocktrans %}</h2>

        <ul>
        {% for kel in related_objects|dictsort:"topic.name" %}
            <li><a href="{{ kel.get_absolute_url }}">{{ kel.topic.name }}</a></li>
        {% endfor %}
        </ul>
    </div>
{% endif %}

{% endblock %}
```

The error is:

> Internal Server Error: /kbase/oplevel/betriebsvereinbarungen
> Traceback (most recent call last):
>   File "venv/lib/python3.4/site-packages/django/db/models/options.py", line 580, in get_field
>     return self.fields_map[field_name]
> KeyError: 'name'
> 
> During handling of the above exception, another exception occurred:
> 
> 
> Traceback (most recent call last):
>   File "venv/lib/python3.4/site-packages/hvad/utils.py", line 126, in __call__
>     return self.real(name, *args, **kwargs)
>   File "venv/lib/python3.4/site-packages/django/db/models/options.py", line 582, in get_field
>     raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, field_name))
> django.core.exceptions.FieldDoesNotExist: Topic has no field named 'name'

Certainly, `Topic` has no field `name`, only a translated field of that name. I'm completely at a loss. I've tried several things like removing lines from the template but it all ends up with that error. It actually makes no difference whether I add the `get_translation_aware_manager` or not so I'm not sure I've done it correct at all. The documentation and StackOverflow have not been of any help so far.

This template and view code was working without the `get_translation_aware_manager` with the old version, so it should be possible to get it to work?

**Comment by spectras** [comment]
Hello,

I believe the issue comes from the magic behind: `ordering = ('name',)`

It will get automatically applied to the translation aware manager, which, unfortunately does not handle it well. As it's not used anyway, you can override it using an `order_by`.
Better yet, drop the `ordering = `, because applying it in *every* query usually does not make sense and incurs additional load on the database — adding an explicit `.order_by()` to the querysets as needed is a better approach.

By the way, you don't need a translation aware manager for this request. This should work (or not work, until you remove the ordering) just the same:
```python
kwargs['related_objects'] = KnowledgeElement.objects.filter(operating_level=self.oplevel)
```
As a rule, keep uses of translation aware manager to the bare minimum. It is a very old piece of hvad, that has not had the new features added and is generally much less used, so more likely to have bugs. Most requests you would use a translation aware manager for usually can be expressed with subqueries.

Now, as you're using `topic` and `topic.name` in your template, I strongly encourage you to explicitly prefetch them, because otherwise, each topic will generate an additional query for the topic itself, plus yet another additional query for the translation.

You would do this that way:
```python
from django.db.models import Prefetch

kwargs['related_objects'] = KnowledgeElement.objects.filter(operating_level=self.oplevel).prefetch_related(
    Prefetch('topic', queryset=Topic.objects.language())
)
```
It would be better with a `select_related`, but Django does not yet support an explicit queryset for this one. Still, 2 queries is better than 1 + 2n.

You might also want to filter out topics which are not translated in current language. Unfortunately, *hvad* does not provide a clean abstraction for this right now, but it's easy to write manually:

```python
kwargs['related_objects'] = KnowledgeElement.objects.filter(
    operating_level=self.oplevel,
    topic__translations__language_code=get_language(),   # only keep items whose topic is available in current language
).prefetch_related(
    Prefetch('topic', queryset=Topic.objects.language())
)
```

I hope it helps.

**Comment by nuarhu** [comment]
Thank you very much. Removing the `ordering` fixed the problem. Actually, in the old version, I was using the meta attribute of the translations dictionary and only moved it to the regular `Meta.ordering` after upgrading because it "seemed to work".

I will also add the prefetch clause.

Again, thanks for taking the time to read through all my code and answer this extensive and understandable!
