### ISSUE TITLE
Translations - uuid as primary key

### ISSUE THREAD

**Issue by eugened19** [KristianOellegaard/django-hvad#299]
Hi guys,

We've switched our models to use uuid as a primary key (instead of default AutoField id) 
1) To adjust schema, we've edited migration files manually.

 name='EntityTranslation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, serialize=False, editable=False, primary_key=True)),
...

2) To make data migration (to adjust foreign keys) we've used approach described here:  https://github.com/KristianOellegaard/django-hvad/issues/277#issuecomment-171988568

3) Everything works fine except one thing.
Every time we're running makemigrations, django (or hvad) tries to remove uuid field from translations table and to replace it with default AutoField id field.

Is it possible to disable this behaviour?
django 1.8,  django-hvad 1.5.0

Thank you!
Eugene

**Comment by spectras** [comment]
Hello,
Thanks for reporting here.

I am not sure which of the two following you are trying to do:

1) You want to change the primary key of your model to use an UUID? This is supposed to work, if that's what you are trying to do, I'll have to investigate to find out why it has this strange behavior.

or

2) You want to change the primary key of the translations to use an UUID? I don't really see the use for this as, normally, the primary key of the translations themselves is hidden from the rest of the code (you cannot access it without going through hvad internals). Unless there is a strongly compelling reason to change it, I would suggest to leave it as is. But if that's *really* something you *must* do, you should keeps its name as `id`, because that name is hardcoded is `hvad`'s core. That is if, in the `EntityTranslation` table, you name your `UUIDField` as `id` instead of `uuid`, it should be detected correctly.

Please tell me if this helps

**Comment by eugened19** [comment]
Thank you for the reply.!

My case in 2)
We're just trying to unify several databases, so data has unique ids across them for replication purposes, so hence come uuids.

I tried renaming uuid field to id, but makemigrations still tries to change it to AutoField.
So, we'll try to make it work without uuids for translation tables. We'll see how it goes.

BTW Case 1) works fine.

**Comment by spectras** [comment]
I don't know if you can use this for replication, but if the main model has a uuid, then the combination `[master_id, language_code]` is guaranteed to be  unique as well
