### ISSUE TITLE
version upgrade: db table name mismatch

### ISSUE THREAD

**Issue by patroqueeet** [KristianOellegaard/django-hvad#302]
dear,

I'm about to upgrade a zurich based package called `onlinegv` (I assume you know the name) to latest Django 1.9 and ran into the following issue:

error is:
```
relation "onlinegv_company_translation" does not exist
```

when I look into the db, I see:

```
public | onlinegv_companytranslation                                  | table    | onlinegv_test
public | onlinegv_companytranslation_id_seq                           | sequence | onlinegv_test
```

I check the entire `hvad` docu and release notes, but didn't find any hint for a change in conventions. where should I look for the resolution?

THX!

**Comment by spectras** [comment]
Hello,
Thanks for reporting here. Are you upgrading django-hvad as well, or just Django itself?
Which versions of hvad and Django are involved in the upgrade?

If upgrading from a (quite) old version of hvad, the table names used to be formed with a setting called `NANI_TABLE_NAME_SEPARATOR`, which was renamed into `HVAD_TABLE_NAME_SEPARATOR`. I think that happened in v0.5.

**Comment by patroqueeet** [comment]
alright, found it while reading `hvad`s code. `HVAD_TABLE_NAME_SEPARATOR` solves it.

**Comment by patroqueeet** [comment]
ha! you we're 9 mins faster. thanks for the fast feedback. and yes, its a 'all packages' upgrade...

THX!

**Comment by spectras** [comment]
Glad you could fix your issue. You should search for the old `NANI_` setting and remove it, to keep settings clean.

The change was documented in http://django-hvad.readthedocs.io/en/latest/public/release_notes.html#id12 (deprecation list, 3rd bullet) but if you don't know what to look for, it's a bit hard to find so long after.

Good luck for converting the rest of the code, if upgrading all packages from 2 years ago that's quite a job. Since I took over maintenance of hvad 2 years ago, I made a point of making the release notes as comprehensive as possible but, should you run into any hvad-related issue, please feel free to open other tickets here.

**Comment by patroqueeet** [comment]
dear,

yeah, I plan to have 2 weeks fulltime for the upgrade. for now it goes ok. the biggest challenge will be to replace a plethora of `.untranslated().use_fallbacks(**fallback_priority)` code. I'm not yet sure what exaclty it does and how to replace it. will be back if I have questions :)

thanks for the fast and timely reply. it's great to know, there is someone to ask...
