### ISSUE TITLE
1.5.1 breaks itself with _language

### ISSUE THREAD

**Issue by patroqueeet** [KristianOellegaard/django-hvad#304]
```
  class TranslatableModelFormMixin(ModelFormMixin, _TransitionObjectMixin):
    ''' ModelFormMixin that works with an TranslatableModelForm in **enforce** mode '''
      query_language_key = 'language'

      def get_language(self):
          # Remove in 1.5
          assert not callable(getattr(self, '_language', None)), (
              'Method \'_language\' has been renamed to \'get_language()\'. '
              'Please update view %s.' % self.__class__.__name__)
          return self.request.GET.get(self.query_language_key) or get_language()
```

fails when I import ```TranslatableModelAdminMixin``` from https://github.com/KristianOellegaard/django-hvad/blob/master/hvad/admin.py#L102

**Comment by spectras** [comment]
Hello,
Thanks for reporting, I'll look into it before tomorrow.

**Comment by patroqueeet** [comment]
hey, that would be really great. it would be an very important fix for me, as I'm using this in dozens of places...

**Comment by spectras** [comment]
I've been investigating a bit, and I fail to figure out how those come to interact.
`TranslatableModelFormMixin` is supposed to be mixed into `FormView` subclasses.
`TranslatableModelAdminMixin` is supposed to be mixed into `ModelAdmin` subclasses.

The fact that the second triggers the assert on the first one suggests at some point you end up mixing in both into the same class. Could you post the class definition that triggers the exception?

**Comment by patroqueeet** [comment]
Dear,

yes, you are fully right. and the reason is I'm using some of the tab generation magic of the admin to use it with my regular forms. nevertheless deprecating a method and leaving it living inside the app does not sound too well :)

Still I'd love to keep using your admin magic along with my forms... :)

**Comment by spectras** [comment]
That's part of the deprecation path, usually I leave a `DeprecationWarning` for 1 or 2 releases, then raise the awareness through `assert`s instead of dropping support silently.

It turns out that those two mixins used to have, by pure chance, a method with common name. And that method was renamed in only one of them. So it complains.

The asserts will be dropped in next release anyway, as part of the regular cleanup of legacy code. But still, the admin functions might change in a way that's incompatible with mixin them into a formview, anytime. If the logic is useful to you, perhaps you should simply copy-paste the relevant methods it into your view?

In hope, in hvad2 (no release planned yet), to drop most of admin's code and go for javascript-powered tabs instead, to provide a friendlier experience.

**Comment by patroqueeet** [comment]
Do I understand right, the admin based `_language` is not related to the method the  DeprecationWarning is checking for?

So your recommendation is to kick my admin mixin usage and move the needed code to my repo. right? From an architectural view it seems to make sense to me, as hvad is not an UI provider :).

**Comment by spectras** [comment]
Exactly, it just so happens that both the admin and the generic views need have a method to get current language. Both methods had the same name and the same implementation, but they were architecturally completely unrelated.

Now, in hvad 1.3, I refactored the generic views so they follow the same conventions as Django's and so all edge cases would be clearly defined (there used to be some undefined behaviors). As part of that refactory, `_language` was renamed to `get_language`.
Deprecation path includes detecting the presence of the deprecated `_language` and raising a warning in hvad 1.3 and 1.4, then raising and AssertionError in hvad 1.5.

The admin side is a distinct module and was left untouched by this refactor, keeping the name `_language`. Merging admin and generic view mixins is completely unexpected, and pure chance leads to the behavior you saw: generic view's deprecation path complaining when it finds admin's internal methods, because it bears the same name as a deprecated generic view method.

Yep, I'd recommend you copy the needed code to your view. Perhaps create your own `LanguageTabsViewMixin` if you use it in several places. As you said, hvad is not an UI provider. It tries to be on par with Django on that matter: generic views, forms and admin. Plus Django REST framework support, which we believe is mandatory in modern websites.

**Comment by patroqueeet** [comment]
perfect. I believe this ticket might be interesting to many others too :)

and thanks again for the timely and precise support!

**Comment by spectras** [comment]
Well, thanks to you for taking the time to report here.
Feel welcome to open other tickets, should you encounter any issue.
