### ISSUE TITLE
Get fieldvalue in current language accesed throw a onetoonefiled

### ISSUE THREAD

**Issue by sowinski** [KristianOellegaard/django-hvad#333]
Hi,

is it possible to select a language in my object instance?
Right now, I am doing something like this:
```python
class MyCity(TranslatableModel):
    
    translations = TranslatedFields (
        slug    = models.CharField(max_length=255),
    )

    city = models.OneToOneField(CityTranslated)

    def get_slug(self):
        lang = get_language().split("-")[0]
        return MyCity.objects.language(lang).get(pk=self.pk)
```
But with this workaround I have to query the db every time.

My problem is, I can't use MyCity.objects.language('en').... in this case, because I am accessing this object from a different query using foreignkey fields.  
```python
cities = CityTranslated.objects.filter(...)`# Need to select the current language here somehow
for city in cities:
    print city.get_slug()
```
Thank You

**Comment by spectras** [comment]
Hello!

Well, as a rule, an instance method such as `get_slug` should use current language, and only current language. If another language is wished for, the calling code should load it before invoking the method.

There are several options to that end:
* Load the city alongside the foreign object by reversing the query, making `language()` available. This usually means two requests instead of one, yielding two disconnected objects.
* Load the city alongside the foreign object, using `prefetch_related` with a custom queryset. This means two requests instead of one, but the objects will reference each other, which is more convenient if you are accessing them through foreign fields.
* Use a custom query (not recommended as it is likely to break when upgrading Django).

To better appreciate your use case, I would need more details on the code that invokes that `get_slug` method and the queries it runs to load both the city and the foreign object.

**Comment by sowinski** [comment]
Thank you for the fast response.

> Well, as a rule, an instance method such as get_slug should use current language, and only current language.

Thats what I want. I don't want to load a different language. 
If I access directly the slug field, I am not always getting the slug in my current language back

```python
class MyCity(TranslatableModel):

    def get_slug(self):
        return self.slug # <-- This is not always giving the current language (don't know why)
```
In my view I am doing this.
```
context['favcities'] = CityTranslated.objects.filter(country=country).order_by('-population')[:80]
```
And accessing my slug field in my template like this:
```
{% for city in favcities %}
{{ city.mycity.slug }}
{% endfor %}
```
Is this the wrong way or is there somewhere a bug?

**Comment by spectras** [comment]
Hmm, this should be correct.
To be exact, that version of `get_slug` will return the slug for whatever language the instance has been loaded with. If not language is loaded, it will attempt to load current language (from `django.utils.translation.get_language()`).

What could go wrong here:
* If the instance already has a language loaded, and it's not the one you want.
* If the language from `get_language()` is incorrect. For instance because django's LocaleMiddleware is not loaded.
* If you expect a fallback chain. That is, if `get_language()` returns "fr-be", hvad will only try that exact language, it will not try "fr" unless you explicitly tell it to.

You can also see odd behaviors in the following conditions:
* If you cache objects between requests. The cached objects will not be reloaded, so they will stick to the old language.
* If you change current language in your view. If you do this, it is important to remember that current language is evaluated at the time the object is actually loaded. For queries, this means when the query is resolved by Django, not when you create the query.

Either way, in your template you access `city.mycity.slug`, which will be very slow as is, because neither `mycity` nor `slug` have been cached, so each item will cause two additional queries. You should prefetch them like this:

```python
# Use this if CityTranslated is a TranslatableModel:

context['favcities'] = (
    CityTranslated.objects.language()
                          .filter(country=country)
                          .select_related('mycity')
                          .order_by('-population')[:80]
)

# Use this if CityTranslated is NOT  a TranslatableModel:

mycity_qs = MyCity.objects.language()

context['favcities'] = (
    CityTranslated.objects.filter(country=country)
                          .prefetch_related(Prefetch('mycity', queryset=mycity_qs))
                          .order_by('-population')[:80]
)
```
Note: `Prefetch` can be imported from `django.db.models`.
