### ISSUE TITLE
Admin does not show untranslated models

### ISSUE THREAD

**Issue by grote** [KristianOellegaard/django-hvad#336]
When you list your models in django admin, only the translated ones are shown. The untranslated ones are hidden as if they do not exist.

A work-around seems to be to override `get_queryset` in `TranslatableAdmin` like so:

```python
    def get_queryset(self, request):
        return self.model.objects.all()
```
Not sure what side-effects that might have though.

**Comment by grote** [comment]
> Not sure what side-effects that might have though.

You loose the ability to the view translations, so that doesn't work.

**Comment by spectras** [comment]
Hello,

Well yes, it is by design since hvad 1.4.0. Even before that, although such models would be shown they emitted an error to the logs. Untranslated models should not exist in a normal hvad setup, because that would make the model incomplete (fields may not exist at all, which is not the same as them having empty/default values).

As you realized while overriding the queryset, fetching the model anyway and emitting errors to the log would make the admin very slow as it forced hvad to either fetch all translations of all models in all languages, or generate an additional query for every fetched model. Just to account for models that should not exist anyway.

FWIW, there was a bug that could lead to the translatable REST support to create untranslated instances when no language and no translatable field was specified on a POST request. It is fixed in the latest release so it creates an empty translation when this happens.

So, I strongly recommend you make sure your apps always create at least one translation for every model. And should you need help to create missing translations, just ask. You should be able to find them using `Model.objects.filter(translations__isnull=True)`

**Comment by grote** [comment]
Thanks for the explanation! Looks like I didn't read all the the documentation properly. I am now ensuring there's always at least one translation.
