### ISSUE TITLE
TranslationsMixin -  translation field is requred on PUT/POST

### ISSUE THREAD

**Issue by danilke** [KristianOellegaard/django-hvad#343]
Hello, I'm using TranslationsMixin:

```
class ProductItemSerializer(TranslationsMixin, WritableNestedModelSerializer):
      ...
     class Meta:
           model = Product
           translations = ProductTranslationSerializer(required=False)
           fields = (
                'id',
                ...
               'translation',
          ) 
```

But when I do PUT request to `/products/1/`
```
{
    "product_groups": {
         "id": 1
     }
}
```
I get error:

```
{
	"translations": [
		"This field is required."
	]
}
``` 
It's possible somehow set `required=False` to translations? Thank you.

**Comment by spectras** [comment]
Hello,

Thanks for opening a ticket here. Before going any further, I believe those things could be a problem:

* The serializer used for translations must be in `Meta` under name `translations_serializer`, not `translations`. Otherwise it won't be used.
* It must be a serializer class, not an instance. For instance, `ProductTranslationSerializer`.
* ~[edit: third point irrelevant]~

Now, one of the main concepts of hvad is an object always has to be complete. That means at no point can an object not have any translation (and if such an object is created, it is an error and the behavior is unspecified).
Here, you are using the `PUT` http verb, which implies the data being sent is a full representation of the object. Therefore it must include at least one translation, or it will break the complete-object rule.

Now if you really insist on doing that, the way you wrote it should work once the items above are fixed. That is, your serializer will override the one provided by `TranslationsMixin`, causing it to no longer be required and forcing `TranslationsMixin` to disable itself.
Be aware that this throws away hvad's checks and you'll have to be very careful not to let your api create orphan models with no translation.

**Comment by danilke** [comment]
Thank you for help!
