### ISSUE TITLE
Search fields and ordering in admin

### ISSUE THREAD

**Issue by ikresoft** [KristianOellegaard/django-hvad#6]
Is it possible to use search fields and ordering in admin on translated fields?

**Comment by jonashagstedt** [comment]
Haven't looked too deeply into this but as @vstoykov said, you can do this and get multiple results back, however you can mitigate that by overriding `get_search_results` in admin:


    def get_search_results(self, request, queryset, search_term):
        qs, use_distinct = super().get_search_results(request, queryset, search_term)
        return qs.distinct(), use_distinct

(Only tested in Django 1.8 and haven't done much testing with it)

**Comment by vstoykov** [comment]
Probably custom TranslatableModelAdmin can overwrite `get_search_results` as @jonashagstedt  suggested but automatically convert filtering rules. The user can still use `field_name` instead of `translations__field_name` and `get_search_results` need to do the heavy lifting.

Probably translatable fields need to be excluded from `search_fields` in the `__init__` and moved to let's say `translatable_search_fields` in order `super().get_search_results()` to not break.
